version: 2
updates:
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: gomod
    schedule:
      interval: monthly
    groups:
      golang-dependencies:
        patterns:
          - "*"
