include:
  - project: 'Northern.tech/Mender/mendertesting'
    file:
      - '.gitlab-ci-check-golang-lint.yml'
      - '.gitlab-ci-check-golang-unittests-v2.yml'
      - '.gitlab-ci-check-license.yml'
      - '.gitlab-ci-github-status-updates.yml'
  - component: gitlab.com/Northern.tech/Mender/mendertesting/commit-lint@master

stages:
  - test
  - publish

test:unit:
  variables:
    TEST_MONGO_URL: "mongodb://mongo"
